### ISSUE TITLE
La url de reMarkets esta usando http en vez de https y ahora eso esta haciendo fallar a getToken

### ISSUE THREAD

**Issue by frossi85** [matbarofex/jsRofex#1]
Hasta hace un tiempo la biblioteca funcionaba bien hasta que detecte que el login no estaba funcionando. Luego de que revisara cual podría ser el problema descubrí que la url para el caso de reMarkets era http y probándolo en Postman descubrí que mientras antes funcionaba ahora devuelve 404.

**Comment by frossi85** [comment]
@augustohassel @fspetale Acá tiene el fix para que puedan hacer un release: https://github.com/matbarofex/jsRofex/pull/2

**Comment by augustohassel** [comment]
Excelente! Hago un merge. Hay que tocar algo más? Te cambio el rol para que puedas hacerlo vos tmb, por si encontras alguna otra cosa!

**Comment by frossi85** [comment]
@augustohassel Vi algunas inconsistencias en lo q devuelve la api o biblioteca en algunos casos. Como devolver Json a veces y en otros un string con el Json adentro. Son cosas que estaría bueno mejorar, pero no eran una traba como lo del protocolo. 

Como prefieren q se trabaje los issues en castellano o ingles?

Como hacen los releases a npmjs? Si hago un cambio a quien le pido un release o como puedo hacer para hacerlo yo. Conocen Github Actions? https://github.com/features/actions

Aca les dejo un ejemplo del archivo q uso yo para auto publicar una biblioteca interna cuando se hace un commit o merge a master:

.github/workflows/publish.yml

```
 This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: '....' #Remover si estan usando npmjs el cual parece que es su caso
        scope: '@...' #Remove si su biblioteca no esta en un scope el cual parece que es su caso
    - run: npm install
      env:
        IF_NPM_TOKEN: ${{ secrets.NpmToken }} # Esto se configura desde las settings del proyecto
    - run: npm run build
      env:
        IF_NPM_TOKEN: ${{ secrets.NpmToken }}
    - run: npm run test
      env:
        IF_NPM_TOKEN: ${{ secrets.NpmToken }}
    - run: npm publish
      env:
        IF_NPM_TOKEN: ${{ secrets.NpmToken }}
```

En la raiz del projecto crean esta estructura/archivo .github/workflows/publish.yml con un cotenido similar al que les mande y entonces en cada merge a master si no hay conflicto de versiones (o sea ya existe esa version) se publicara automaticamente la nueva version.
